"""add credentials

Revision ID: 23ee844c0f94
Revises: af27f922e33a
Create Date: 2024-08-23 07:46:56.739342

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23ee844c0f94"
down_revision: Union[str, None] = "af27f922e33a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column(
            "credential_type",
            sa.Enum("SERVICE_ACCOUNT_KEY", "SECRET", name="credentialtype"),
            nullable=False,
        ),
        sa.Column("credential_value", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization_references.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_credentials_created_at"), "credentials", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_credentials_updated_at"), "credentials", ["updated_at"], unique=False
    )
    op.drop_column("projects", "is_user_default")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("is_user_default", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_credentials_updated_at"), table_name="credentials")
    op.drop_index(op.f("ix_credentials_created_at"), table_name="credentials")
    op.drop_table("credentials")
    # ### end Alembic commands ###
