"""add enum

Revision ID: 0608e22a0f94
Revises: 23ee844c0f94
Create Date: 2024-08-24 21:40:05.845239

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0608e22a0f94"
down_revision: Union[str, None] = "23ee844c0f94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
