"""allow creds to be associated with projects, add name

Revision ID: 3b56576fb4ed
Revises: 573ce91abfad
Create Date: 2024-08-25 03:58:08.078095

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b56576fb4ed"
down_revision: Union[str, None] = "573ce91abfad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("credentials", sa.Column("name", sa.String(), nullable=False))
    op.add_column("packages", sa.Column("private", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("packages", "private")
    op.drop_column("credentials", "name")
    # ### end Alembic commands ###
