"""drop column

Revision ID: 14da7f07a83a
Revises: 124e09977952
Create Date: 2024-08-27 18:10:44.978756

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14da7f07a83a"
down_revision: Union[str, None] = "124e09977952"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_packages", "deploy_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_packages",
        sa.Column(
            "deploy_status",
            postgresql.ENUM(
                "NOT_DEPLOYED", "DEPLOYING", "DEPLOYED", "FAILED", name="deploy_status"
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
