"""enums

Revision ID: 124e09977952
Revises: 4984cf81e7b9
Create Date: 2024-08-27 17:12:40.774582

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "124e09977952"
down_revision: Union[str, None] = "4984cf81e7b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
