"""add enum two

Revision ID: 573ce91abfad
Revises: 0608e22a0f94
Create Date: 2024-08-24 21:41:25.379531

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "573ce91abfad"
down_revision: Union[str, None] = "0608e22a0f94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
