/**
 * Canvas API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProjectPackageStatus from './ProjectPackageStatus';

/**
 * The AppSchemasProvisionerProjectPackageProjectPackageUpdate model module.
 * @module model/AppSchemasProvisionerProjectPackageProjectPackageUpdate
 * @version 0.1.0
 */
class AppSchemasProvisionerProjectPackageProjectPackageUpdate {
  /**
   * Constructs a new <code>AppSchemasProvisionerProjectPackageProjectPackageUpdate</code>.
   * @alias module:model/AppSchemasProvisionerProjectPackageProjectPackageUpdate
   * @param deployStatus {module:model/ProjectPackageStatus}
   */
  constructor(deployStatus) {
    AppSchemasProvisionerProjectPackageProjectPackageUpdate.initialize(
      this,
      deployStatus
    );
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, deployStatus) {
    obj['deploy_status'] = deployStatus;
  }

  /**
   * Constructs a <code>AppSchemasProvisionerProjectPackageProjectPackageUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AppSchemasProvisionerProjectPackageProjectPackageUpdate} obj Optional instance to populate.
   * @return {module:model/AppSchemasProvisionerProjectPackageProjectPackageUpdate} The populated <code>AppSchemasProvisionerProjectPackageProjectPackageUpdate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj =
        obj || new AppSchemasProvisionerProjectPackageProjectPackageUpdate();

      if (data.hasOwnProperty('deploy_status')) {
        obj['deploy_status'] = ProjectPackageStatus.constructFromObject(
          data['deploy_status']
        );
      }
      if (data.hasOwnProperty('output_data')) {
        obj['output_data'] = ApiClient.convertToType(
          data['output_data'],
          Object
        );
      }
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>AppSchemasProvisionerProjectPackageProjectPackageUpdate</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AppSchemasProvisionerProjectPackageProjectPackageUpdate</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of AppSchemasProvisionerProjectPackageProjectPackageUpdate.RequiredProperties) {
      if (!data.hasOwnProperty(property)) {
        throw new Error(
          'The required field `' +
            property +
            '` is not found in the JSON data: ' +
            JSON.stringify(data)
        );
      }
    }

    return true;
  }
}

AppSchemasProvisionerProjectPackageProjectPackageUpdate.RequiredProperties = [
  'deploy_status',
];

/**
 * @member {module:model/ProjectPackageStatus} deploy_status
 */
AppSchemasProvisionerProjectPackageProjectPackageUpdate.prototype[
  'deploy_status'
] = undefined;

/**
 * @member {Object} output_data
 */
AppSchemasProvisionerProjectPackageProjectPackageUpdate.prototype[
  'output_data'
] = undefined;

export default AppSchemasProvisionerProjectPackageProjectPackageUpdate;
