/**
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CredentialUpdate model module.
 * @module model/CredentialUpdate
 * @version 0.1.0
 */
class CredentialUpdate {
  /**
   * Constructs a new <code>CredentialUpdate</code>.
   * @alias module:model/CredentialUpdate
   */
  constructor() {
    CredentialUpdate.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj) {}

  /**
   * Constructs a <code>CredentialUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CredentialUpdate} obj Optional instance to populate.
   * @return {module:model/CredentialUpdate} The populated <code>CredentialUpdate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CredentialUpdate();

      if (data.hasOwnProperty('credential_value')) {
        obj['credential_value'] = ApiClient.convertToType(
          data['credential_value'],
          'String'
        );
      }
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>CredentialUpdate</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CredentialUpdate</code>.
   */
  static validateJSON(data) {
    // ensure the json data is a string
    if (
      data['credential_value'] &&
      !(
        typeof data['credential_value'] === 'string' ||
        data['credential_value'] instanceof String
      )
    ) {
      throw new Error(
        'Expected the field `credential_value` to be a primitive type in the JSON string but got ' +
          data['credential_value']
      );
    }

    return true;
  }
}

/**
 * @member {String} credential_value
 */
CredentialUpdate.prototype['credential_value'] = undefined;

export default CredentialUpdate;
