/**
 * Canvas API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
 * Enum class ProjectPackageStatus.
 * @enum {}
 * @readonly
 */
export default class ProjectPackageStatus {
  /**
   * value: "NOT_DEPLOYED"
   * @const
   */
  NOT_DEPLOYED = 'NOT_DEPLOYED';

  /**
   * value: "DEPLOYING"
   * @const
   */
  DEPLOYING = 'DEPLOYING';

  /**
   * value: "DESTROYING"
   * @const
   */
  DESTROYING = 'DESTROYING';

  /**
   * value: "DEPLOYED"
   * @const
   */
  DEPLOYED = 'DEPLOYED';

  /**
   * value: "FAILED"
   * @const
   */
  FAILED = 'FAILED';

  /**
   * Returns a <code>ProjectPackageStatus</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/ProjectPackageStatus} The enum <code>ProjectPackageStatus</code> value.
   */
  static constructFromObject(object) {
    return object;
  }
}
