/**
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import Connection from './model/Connection';
import ConnectionCreate from './model/ConnectionCreate';
import HTTPValidationError from './model/HTTPValidationError';
import Package from './model/Package';
import PackageCreate from './model/PackageCreate';
import PackageUpdate from './model/PackageUpdate';
import Project from './model/Project';
import ProjectCreate from './model/ProjectCreate';
import ProjectUpdate from './model/ProjectUpdate';
import ValidationError from './model/ValidationError';
import ValidationErrorLocInner from './model/ValidationErrorLocInner';
import DefaultApi from './api/DefaultApi';
import PackagesApi from './api/PackagesApi';
import ProjectApi from './api/ProjectApi';

/**
 * JS API client generated by OpenAPI Generator.<br>
 * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
 * <p>
 * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
 * <pre>
 * var PlatformApi = require('index'); // See note below*.
 * var xxxSvc = new PlatformApi.XxxApi(); // Allocate the API class we're going to use.
 * var yyyModel = new PlatformApi.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
 * and put the application logic within the callback function.</em>
 * </p>
 * <p>
 * A non-AMD browser application (discouraged) might do something like this:
 * <pre>
 * var xxxSvc = new PlatformApi.XxxApi(); // Allocate the API class we're going to use.
 * var yyy = new PlatformApi.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * </p>
 * @module index
 * @version 0.1.0
 */
export {
  /**
   * The ApiClient constructor.
   * @property {module:ApiClient}
   */
  ApiClient,

  /**
   * The Connection model constructor.
   * @property {module:model/Connection}
   */
  Connection,

  /**
   * The ConnectionCreate model constructor.
   * @property {module:model/ConnectionCreate}
   */
  ConnectionCreate,

  /**
   * The HTTPValidationError model constructor.
   * @property {module:model/HTTPValidationError}
   */
  HTTPValidationError,

  /**
   * The Package model constructor.
   * @property {module:model/Package}
   */
  Package,

  /**
   * The PackageCreate model constructor.
   * @property {module:model/PackageCreate}
   */
  PackageCreate,

  /**
   * The PackageUpdate model constructor.
   * @property {module:model/PackageUpdate}
   */
  PackageUpdate,

  /**
   * The Project model constructor.
   * @property {module:model/Project}
   */
  Project,

  /**
   * The ProjectCreate model constructor.
   * @property {module:model/ProjectCreate}
   */
  ProjectCreate,

  /**
   * The ProjectUpdate model constructor.
   * @property {module:model/ProjectUpdate}
   */
  ProjectUpdate,

  /**
   * The ValidationError model constructor.
   * @property {module:model/ValidationError}
   */
  ValidationError,

  /**
   * The ValidationErrorLocInner model constructor.
   * @property {module:model/ValidationErrorLocInner}
   */
  ValidationErrorLocInner,

  /**
   * The DefaultApi service constructor.
   * @property {module:api/DefaultApi}
   */
  DefaultApi,

  /**
   * The PackagesApi service constructor.
   * @property {module:api/PackagesApi}
   */
  PackagesApi,

  /**
   * The ProjectApi service constructor.
   * @property {module:api/ProjectApi}
   */
  ProjectApi,
};
