/**
 * Canvas API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd() + '/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd() + '/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CanvasApi);
  }
})(this, function (expect, CanvasApi) {
  'use strict';

  var instance;

  beforeEach(function () {
    instance = new CanvasApi.DefaultApi();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') return object[getter]();
    else return object[property];
  };

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') object[setter](value);
    else object[property] = value;
  };

  describe('DefaultApi', function () {
    describe('createConnectionProjectsProjectIdConnectionsPost', function () {
      it('should call createConnectionProjectsProjectIdConnectionsPost successfully', function (done) {
        //uncomment below and update the code to test createConnectionProjectsProjectIdConnectionsPost
        //instance.createConnectionProjectsProjectIdConnectionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createCredentialCredentialsPost', function () {
      it('should call createCredentialCredentialsPost successfully', function (done) {
        //uncomment below and update the code to test createCredentialCredentialsPost
        //instance.createCredentialCredentialsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createGlobalPackagePackagesPost', function () {
      it('should call createGlobalPackagePackagesPost successfully', function (done) {
        //uncomment below and update the code to test createGlobalPackagePackagesPost
        //instance.createGlobalPackagePackagesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createOrUpdateGlobalPackagePackagesCreateOrUpdatePost', function () {
      it('should call createOrUpdateGlobalPackagePackagesCreateOrUpdatePost successfully', function (done) {
        //uncomment below and update the code to test createOrUpdateGlobalPackagePackagesCreateOrUpdatePost
        //instance.createOrUpdateGlobalPackagePackagesCreateOrUpdatePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createProjectProjectsPost', function () {
      it('should call createProjectProjectsPost successfully', function (done) {
        //uncomment below and update the code to test createProjectProjectsPost
        //instance.createProjectProjectsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteConnectionProjectsProjectIdSourceSourcePackageIdTargetTargetPackageIdDelete', function () {
      it('should call deleteConnectionProjectsProjectIdSourceSourcePackageIdTargetTargetPackageIdDelete successfully', function (done) {
        //uncomment below and update the code to test deleteConnectionProjectsProjectIdSourceSourcePackageIdTargetTargetPackageIdDelete
        //instance.deleteConnectionProjectsProjectIdSourceSourcePackageIdTargetTargetPackageIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteConnectionsByTargetProjectsProjectIdConnectionsByTargetTargetPackageIdDelete', function () {
      it('should call deleteConnectionsByTargetProjectsProjectIdConnectionsByTargetTargetPackageIdDelete successfully', function (done) {
        //uncomment below and update the code to test deleteConnectionsByTargetProjectsProjectIdConnectionsByTargetTargetPackageIdDelete
        //instance.deleteConnectionsByTargetProjectsProjectIdConnectionsByTargetTargetPackageIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCredentialCredentialsCredentialIdDelete', function () {
      it('should call deleteCredentialCredentialsCredentialIdDelete successfully', function (done) {
        //uncomment below and update the code to test deleteCredentialCredentialsCredentialIdDelete
        //instance.deleteCredentialCredentialsCredentialIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteProjectProjectsProjectIdDelete', function () {
      it('should call deleteProjectProjectsProjectIdDelete successfully', function (done) {
        //uncomment below and update the code to test deleteProjectProjectsProjectIdDelete
        //instance.deleteProjectProjectsProjectIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCredentialCredentialsCredentialIdGet', function () {
      it('should call getCredentialCredentialsCredentialIdGet successfully', function (done) {
        //uncomment below and update the code to test getCredentialCredentialsCredentialIdGet
        //instance.getCredentialCredentialsCredentialIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProjectProjectsProjectIdGet', function () {
      it('should call getProjectProjectsProjectIdGet successfully', function (done) {
        //uncomment below and update the code to test getProjectProjectsProjectIdGet
        //instance.getProjectProjectsProjectIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAllPackagesPackagesGet', function () {
      it('should call listAllPackagesPackagesGet successfully', function (done) {
        //uncomment below and update the code to test listAllPackagesPackagesGet
        //instance.listAllPackagesPackagesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listConnectionsProjectsProjectIdConnectionsGet', function () {
      it('should call listConnectionsProjectsProjectIdConnectionsGet successfully', function (done) {
        //uncomment below and update the code to test listConnectionsProjectsProjectIdConnectionsGet
        //instance.listConnectionsProjectsProjectIdConnectionsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCredentialsCredentialsGet', function () {
      it('should call listCredentialsCredentialsGet successfully', function (done) {
        //uncomment below and update the code to test listCredentialsCredentialsGet
        //instance.listCredentialsCredentialsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listProjectsProjectsGet', function () {
      it('should call listProjectsProjectsGet successfully', function (done) {
        //uncomment below and update the code to test listProjectsProjectsGet
        //instance.listProjectsProjectsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rootGet', function () {
      it('should call rootGet successfully', function (done) {
        //uncomment below and update the code to test rootGet
        //instance.rootGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCredentialCredentialsCredentialIdPatch', function () {
      it('should call updateCredentialCredentialsCredentialIdPatch successfully', function (done) {
        //uncomment below and update the code to test updateCredentialCredentialsCredentialIdPatch
        //instance.updateCredentialCredentialsCredentialIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateProjectProjectsProjectIdPatch', function () {
      it('should call updateProjectProjectsProjectIdPatch successfully', function (done) {
        //uncomment below and update the code to test updateProjectProjectsProjectIdPatch
        //instance.updateProjectProjectsProjectIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });
});
