/**
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PlatformApi);
  }
}(this, function(expect, PlatformApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PlatformApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('createConnectionProjectsProjectIdConnectionsPost', function() {
      it('should call createConnectionProjectsProjectIdConnectionsPost successfully', function(done) {
        //uncomment below and update the code to test createConnectionProjectsProjectIdConnectionsPost
        //instance.createConnectionProjectsProjectIdConnectionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createPackageProjectsProjectIdPackagesPost', function() {
      it('should call createPackageProjectsProjectIdPackagesPost successfully', function(done) {
        //uncomment below and update the code to test createPackageProjectsProjectIdPackagesPost
        //instance.createPackageProjectsProjectIdPackagesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createProjectProjectsPost', function() {
      it('should call createProjectProjectsPost successfully', function(done) {
        //uncomment below and update the code to test createProjectProjectsPost
        //instance.createProjectProjectsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteConnectionProjectsProjectIdConnectionsConnectionIdDelete', function() {
      it('should call deleteConnectionProjectsProjectIdConnectionsConnectionIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteConnectionProjectsProjectIdConnectionsConnectionIdDelete
        //instance.deleteConnectionProjectsProjectIdConnectionsConnectionIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletePackageProjectsProjectIdPackagesPackageIdDelete', function() {
      it('should call deletePackageProjectsProjectIdPackagesPackageIdDelete successfully', function(done) {
        //uncomment below and update the code to test deletePackageProjectsProjectIdPackagesPackageIdDelete
        //instance.deletePackageProjectsProjectIdPackagesPackageIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteProjectProjectsProjectIdDelete', function() {
      it('should call deleteProjectProjectsProjectIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteProjectProjectsProjectIdDelete
        //instance.deleteProjectProjectsProjectIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deployPackageProjectsProjectIdPackagesPackageIdDeployPost', function() {
      it('should call deployPackageProjectsProjectIdPackagesPackageIdDeployPost successfully', function(done) {
        //uncomment below and update the code to test deployPackageProjectsProjectIdPackagesPackageIdDeployPost
        //instance.deployPackageProjectsProjectIdPackagesPackageIdDeployPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('destroyPackageProjectsProjectIdPackagesPackageIdDestroyDelete', function() {
      it('should call destroyPackageProjectsProjectIdPackagesPackageIdDestroyDelete successfully', function(done) {
        //uncomment below and update the code to test destroyPackageProjectsProjectIdPackagesPackageIdDestroyDelete
        //instance.destroyPackageProjectsProjectIdPackagesPackageIdDestroyDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAllPackagesPackagesGet', function() {
      it('should call listAllPackagesPackagesGet successfully', function(done) {
        //uncomment below and update the code to test listAllPackagesPackagesGet
        //instance.listAllPackagesPackagesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listConnectionsProjectsProjectIdConnectionsGet', function() {
      it('should call listConnectionsProjectsProjectIdConnectionsGet successfully', function(done) {
        //uncomment below and update the code to test listConnectionsProjectsProjectIdConnectionsGet
        //instance.listConnectionsProjectsProjectIdConnectionsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listPackagesProjectsProjectIdPackagesGet', function() {
      it('should call listPackagesProjectsProjectIdPackagesGet successfully', function(done) {
        //uncomment below and update the code to test listPackagesProjectsProjectIdPackagesGet
        //instance.listPackagesProjectsProjectIdPackagesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listProjectsProjectsGet', function() {
      it('should call listProjectsProjectsGet successfully', function(done) {
        //uncomment below and update the code to test listProjectsProjectsGet
        //instance.listProjectsProjectsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatePackageProjectsProjectIdPackagesPackageIdPatch', function() {
      it('should call updatePackageProjectsProjectIdPackagesPackageIdPatch successfully', function(done) {
        //uncomment below and update the code to test updatePackageProjectsProjectIdPackagesPackageIdPatch
        //instance.updatePackageProjectsProjectIdPackagesPackageIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateProjectProjectsProjectIdPatch', function() {
      it('should call updateProjectProjectsProjectIdPatch successfully', function(done) {
        //uncomment below and update the code to test updateProjectProjectsProjectIdPatch
        //instance.updateProjectProjectsProjectIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
