"""init db

Revision ID: 3d47e95c1aaf
Revises:
Create Date: 2024-08-16 23:26:32.128513

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d47e95c1aaf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_references",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_references_created_at"),
        "organization_references",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_references_name"),
        "organization_references",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_references_updated_at"),
        "organization_references",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "user_references",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("google_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_references_created_at"),
        "user_references",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_references_email"), "user_references", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_user_references_google_id"),
        "user_references",
        ["google_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_references_updated_at"),
        "user_references",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_references.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_api_tokens_created_at"), "api_tokens", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_api_tokens_token"), "api_tokens", ["token"], unique=True)
    op.create_index(
        op.f("ix_api_tokens_updated_at"), "api_tokens", ["updated_at"], unique=False
    )
    op.create_table(
        "credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("credential_type", sa.String(), nullable=True),
        sa.Column("encrypted_data", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization_references.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_credentials_created_at"), "credentials", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_credentials_name"), "credentials", ["name"], unique=False)
    op.create_index(
        op.f("ix_credentials_updated_at"), "credentials", ["updated_at"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("is_user_default", sa.Boolean(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization_references.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_projects_created_at"), "projects", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_index(
        op.f("ix_projects_updated_at"), "projects", ["updated_at"], unique=False
    )
    op.create_table(
        "chats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("is_user_default", sa.Boolean(), nullable=True),
        sa.Column("is_starred", sa.Boolean(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chats_created_at"), "chats", ["created_at"], unique=False)
    op.create_index(op.f("ix_chats_name"), "chats", ["name"], unique=False)
    op.create_index(op.f("ix_chats_updated_at"), "chats", ["updated_at"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("is_context_file", sa.Boolean(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.Column("content_raw", sa.JSON(), nullable=True),
        sa.Column("is_tool_message", sa.Boolean(), nullable=True),
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_messages_created_at"),
        "chat_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_messages_updated_at"),
        "chat_messages",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_messages_updated_at"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_created_at"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_chats_updated_at"), table_name="chats")
    op.drop_index(op.f("ix_chats_name"), table_name="chats")
    op.drop_index(op.f("ix_chats_created_at"), table_name="chats")
    op.drop_table("chats")
    op.drop_index(op.f("ix_projects_updated_at"), table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_created_at"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_credentials_updated_at"), table_name="credentials")
    op.drop_index(op.f("ix_credentials_name"), table_name="credentials")
    op.drop_index(op.f("ix_credentials_created_at"), table_name="credentials")
    op.drop_table("credentials")
    op.drop_index(op.f("ix_api_tokens_updated_at"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_token"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_created_at"), table_name="api_tokens")
    op.drop_table("api_tokens")
    op.drop_index(op.f("ix_user_references_updated_at"), table_name="user_references")
    op.drop_index(op.f("ix_user_references_google_id"), table_name="user_references")
    op.drop_index(op.f("ix_user_references_email"), table_name="user_references")
    op.drop_index(op.f("ix_user_references_created_at"), table_name="user_references")
    op.drop_table("user_references")
    op.drop_index(
        op.f("ix_organization_references_updated_at"),
        table_name="organization_references",
    )
    op.drop_index(
        op.f("ix_organization_references_name"), table_name="organization_references"
    )
    op.drop_index(
        op.f("ix_organization_references_created_at"),
        table_name="organization_references",
    )
    op.drop_table("organization_references")
    # ### end Alembic commands ###
