/**
 * Canvas API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd() + '/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd() + '/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CanvasApi);
  }
})(this, function (expect, CanvasApi) {
  'use strict';

  var instance;

  beforeEach(function () {
    instance = new CanvasApi.Connection();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') return object[getter]();
    else return object[property];
  };

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') object[setter](value);
    else object[property] = value;
  };

  describe('Connection', function () {
    it('should create an instance of Connection', function () {
      // uncomment below and update the code to test Connection
      //var instance = new CanvasApi.Connection();
      //expect(instance).to.be.a(CanvasApi.Connection);
    });

    it('should have the property sourcePackageId (base name: "source_package_id")', function () {
      // uncomment below and update the code to test the property sourcePackageId
      //var instance = new CanvasApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property targetPackageId (base name: "target_package_id")', function () {
      // uncomment below and update the code to test the property targetPackageId
      //var instance = new CanvasApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property sourceHandle (base name: "source_handle")', function () {
      // uncomment below and update the code to test the property sourceHandle
      //var instance = new CanvasApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property targetHandle (base name: "target_handle")', function () {
      // uncomment below and update the code to test the property targetHandle
      //var instance = new CanvasApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function () {
      // uncomment below and update the code to test the property id
      //var instance = new CanvasApi.Connection();
      //expect(instance).to.be();
    });

    it('should have the property projectId (base name: "project_id")', function () {
      // uncomment below and update the code to test the property projectId
      //var instance = new CanvasApi.Connection();
      //expect(instance).to.be();
    });
  });
});
