/**
 * Canvas API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User from '../model/User';

/**
 * Me service.
 * @module api/MeApi
 * @version 0.1.0
 */
export default class MeApi {
  /**
   * Constructs a new MeApi.
   * @alias module:api/MeApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
   * Callback function to receive the result of the readUsersMeMeGet operation.
   * @callback module:api/MeApi~readUsersMeMeGetCallback
   * @param {String} error Error message, if any.
   * @param {module:model/User} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Read Users Me
   * @param {module:api/MeApi~readUsersMeMeGetCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link module:model/User}
   */
  readUsersMeMeGet(callback) {
    let postBody = null;

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ['application/json'];
    let returnType = User;
    return this.apiClient.callApi(
      '/me',
      'GET',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null,
      callback
    );
  }
}
